# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: mysql-pv-volumes
#   labels:
#     type: local
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 512Mi
#   accessModes:
#     - ReadWriteMany
#   hostPath:
#     path: "/mnt/data"
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mysql-pv-claims
# spec:
#   storageClassName: manual
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 512Mi
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
spec:
  selector:
    matchLabels:
      app: mysql-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
      - image: mysql:latest
        name: mysql-db
        readinessProbe:
          tcpSocket:
            port: 3306 # The port MySQL is listening on
          initialDelaySeconds: 15 # Wait 15 seconds before the first probe
          periodSeconds: 10 # Check every 10 seconds
          timeoutSeconds: 5 # Timeout after 5 seconds if no connection is established
          successThreshold: 1 # Number of consecutive successes for the probe to be considered successful
          failureThreshold: 3 # Number of consecutive failures for the probe to be considered failed
        env:
        - name: MYSQL_USER
          value: {{ .Values.mysql.user}}
        - name: MYSQL_PASSWORD
          value: {{ .Values.mysql.password}}                
        - name: MYSQL_DATABASE
          value: {{ .Values.mysql.database}}                
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.mysql.rootPassword}}                            
        ports:
        - containerPort: 3306    
      #   volumeMounts:
      #   - name: mysql-persistent-storage
      #     mountPath: /var/lib/mysql
      # volumes:
      # - name: mysql-persistent-storage
      #   persistentVolumeClaim:
      #     claimName: mysql-pv-claims
      nodeSelector:
        deployment_node: lenovo_node          
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.host}}
spec:
  ports:
  - port: 3306
  selector:
    app: mysql-db